language: php

php:
  - 5.4

env:
 - GROUP=Joomla2 ENV=joomla2
 - GROUP=Joomla3 ENV=joomla3

before_script:
  - phpenv config-add .travis.ini
  - phpenv rehash

  # Install Apache
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl > /dev/null
  - sudo chmod 777 -R /home/travis/build/PATH_TO_EXTENSION/ #This is the path to the folder of extension/web application on travis
  - sudo ln -s /home/travis/build/PATH_TO_EXTENSION/tests/system/joomla-cms2/ /var/www/joomla-cms2 #Add joomla to apache htdocs
  - sudo ln -s /home/travis/build/PATH_TO_EXTENSION/tests/system/joomla-cms3/ /var/www/joomla-cms3 #Add joomla to apache htdocs
  - sudo sed -i -e "s,AllowOverride[ ]None,AllowOverride All,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart
  - composer install --dev --prefer-dist

  # XVFB
  - "export DISPLAY=:99.0"
  - "Xvfb :99.0 -extension RANDR > /dev/null &"

  # Window manager
  - echo "c10"
  - "sudo apt-get install fluxbox -y --force-yes"
  - echo "c11"
  - "fluxbox &"

  # Selenium server
  - "wget http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar"
  - "java -jar selenium-server-standalone-2.41.0.jar > /dev/null 2>/dev/null &"
  - sleep 20


script:
  - php .travis/phppec.php component/ libraries/ modules/ plugins/
  - php .travis/phpcs.php
  - php .travis/phpmd.php
  # system testing starts
  - php .travis/traviswebserverckecker.php http://localhost/joomla-cms2/installation/index.php # Test apache
  - php .travis/traviswebserverckecker.php http://localhost/joomla-cms3/installation/index.php # Test apache
  - mv tests/acceptance.suite.dist.yml tests/acceptance.suite.yml # Create travis system tests config file
  - "wget http://codeception.com/codecept.phar"
  - php vendor/bin/codecept build
  - php codecept.phar run acceptance -g $GROUP --env $ENV
  #- php codecept.phar run acceptance -g Joomla3 --env joomla3
  - php .travis/codeceptionerror2slack.php # Send found errors into redSHOP slackchat

notifications:
  slack:
  #  secure: hzld/tHdB5/KjVk2Jqc8gaHeoljg2mw2jE/X2Y4xyneST88DrQzFC8YjmneeFMKJHZ4UglrZr9QaO4bnr+KiaUX4ocgbaHKSlXBWpCTTWTfb+RhE+juyD+pd3uMyJ8iPRrHGxGtFswea68NFfwV5D0qWJfkaZ1aQSD4x/cV3FDs=
